---
Name: mailblockconfig
After:
  - '#mailer'
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Mailblock\extensions\MailblockSiteConfig

SilverStripe\SiteConfig\SiteConfigLeftAndMain:
  extensions:
    - Mailblock\extensions\MailblockSiteConfigLeftAndMain

SilverStripe\Core\Injector\Injector:
  Symfony\Component\EventDispatcher\EventDispatcherInterface.mailer:
    calls:
      - [addSubscriber, ['%$Mailblock\Email\MailblockMailSubscriber']]
